In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('19Gx363j3wl5Y7rA9-zvPMDBAFzx1GE79')

In [ ]:
# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor

A tensor can be constructed from a Python list or sequence using the torch.tensor() constructor:

In [ ]:
# Example 1 - working (change this)
torch.tensor([[1, 2, 3], [6., 5., 8.]])

tensor([[1., 2., 3.],
        [6., 5., 8.]])

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type (Ex. Float)

In [ ]:
# Example 2 - working
import numpy as np
torch.tensor(np.array([[1, 2, 3], [6., 5., 8.]]))

tensor([[1., 2., 3.],
        [6., 5., 8.]], dtype=torch.float64)

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[3, 5, 7, 8], [3, 4, 5]])

ValueError: expected sequence of length 4 at dim 1 (got 3)

Tensors can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.

A ValueError is thrown because the lengths of the rows [3, 5, 7, 8] and [3, 4, 5] don't match.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "asaane88/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/asaane88/01-tensor-operations


'https://jovian.ai/asaane88/01-tensor-operations'

## Function 2 - torch.nn

A fully-connected ReLU network with one hidden layer, trained to predict y from x by minimizing squared Euclidean distance.

This implementation uses the nn package from PyTorch to build the network. The nn package defines a set of Modules, which you can think of as a neural network layer that has produces output from input and may have some trainable weights.

In [ ]:
# Example 1 - working
import torch

N, D_in, H, D_out = 800, 9900, 1100, 2000

x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

1. N is batch size; D_in is input dimension;
2. H is hidden dimension; D_out is output dimension.
3. Create random Tensors to hold inputs and outputs (x and y)

In [ ]:
# Example 2 - working
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

1. Use the nn package to define our model as a sequence of layers. 
2. nn.Sequential is a Module which contains other Modules, and applies them in sequence to produce its output. 
3. Each Linear Module computes output from input using a linear function, and holds internal Tensors for its weight and bias.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
loss_fn = torch.nn.MSELoss(reduction='sum')

1. The nn package also contains definitions of popular loss functions; 
2. in this case we will use Mean Squared Error (MSE) as our loss function.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "asaane88/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/asaane88/01-tensor-operations


'https://jovian.ai/asaane88/01-tensor-operations'

## Function 3 - torch.hub

Pytorch Hub is a pre-trained model repository designed to facilitate research reproducibility.

Pytorch Hub supports publishing pre-trained models(model definitions and pre-trained weights) to a github repository by adding a simple hubconf.py file.

hubconf.py can have multiple entrypoints. Each entrypoint is defined as a python function (example: a pre-trained model you want to publish).

In [ ]:
# Example 1 - working
dependencies = ['torch']
from torchvision.models.resnet import resnet18 as _resnet18

# Top level data directory. Here we assume the format of the directory conforms
#   to the ImageFolder structure
data_dir = "/hymenoptera_data"
# Models to choose from [resnet, alexnet, vgg, squeezenet, densenet, inception]
model_name = "resnet"
# Number of classes in the dataset
num_classes = 2
# Batch size for training (change depending on how much memory you have)
batch_size = 8
# Number of epochs to train for
num_epochs = 15
# Flag for feature extracting. When False, we finetune the whole model,
#   when True we only update the reshaped layer params
feature_extract = True


def initialize_model(model_name, num_classes, feature_extract, use_pretrained=True):
    # Initialize these variables which will be set in this if statement. Each of these
    #   variables is model specific.
    model_ft = None
    input_size = 0

    if model_name == "resnet":
        """ Resnet18
        """
        model_ft = models.resnet18(pretrained=use_pretrained)
        set_parameter_requires_grad(model_ft, feature_extract)
        num_ftrs = model_ft.fc.in_features
        model_ft.fc = nn.Linear(num_ftrs, num_classes)
        input_size = 224
        return model_ft, input_size

1. dependencies variable is a list of package names required to load the model.
2. ResNet-18 is a convolutional neural network that is 18 layers deep. You can load a pretrained version of the network trained on more than a million images from the ImageNet database
3. resnet18 is the name of entrypoint to create a hubconf.py file. 
4. args and kwargs are passed along to the real callable function.

In [ ]:
# Example 2 - working

# Initialize the model for this run
model_ft, input_size = initialize_model(model_name, num_classes, feature_extract, use_pretrained=True)

# Print the model we just instantiated
print(model_ft)

1. Call the model, load pretrained weights

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
if pretrained:
    dirname = os.path.dirname(__file__)
    checkpoint = os.path.join(dirname, <RELATIVE_PATH_TO_CHECKPOINT>)
    state_dict = torch.load(checkpoint)
    model.load_state_dict(state_dict)

    checkpoint = 'https://download.pytorch.org/models/resnet18-5c106cde.pth'
    model.load_state_dict(torch.hub.load_state_dict_from_url(checkpoint, progress=False))

1. For checkpoint saved in local github repo, e.g. <RELATIVE_PATH_TO_CHECKPOINT>=weights/save.pth
2. For checkpoint saved elsewhere

In transfer learning, The performance of finetuning vs. feature extracting depends largely on the dataset but in general both transfer learning methods produce favorable results in terms of training time and overall accuracy versus a model trained from scratch. 

Pretrained Models can be used to reduce training time and achieve better results on large size image datasets.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "asaane88/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/asaane88/01-tensor-operations


'https://jovian.ai/asaane88/01-tensor-operations'

## Function 4 - torch.arange

Returns a one dimension tensor with the parameters chosen: START, END (only one mandatory) and STEP.

In [ ]:
# Example 1 - working
torch.arange(8)

tensor([0, 1, 2, 3, 4, 5, 6, 7])

Simple tensor created with only one argument (END) given. Therefore, START is by default 0 and the END is not included, we get up to 7 (END -1).

In [ ]:
# Example 2 - working
torch.arange(2, 100, 5)

Tensor that starts with 2 (included), and the following values are added by 5 (STEP). until we reach 99 (END-1). Note that the last value won't be higher than END).

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(5, 3, 4)

RuntimeError: upper bound and larger bound inconsistent with step sign

In this simple example, when START is bigger than END, the spet sign must be negative in the sense that it is counting backwards.

Closing comments about when to use this function:
This simple function can be very useful to create Tensors of 1 dimensions and, if more dimensions are required, we can just create them withing the bigger one.

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "asaane88/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/asaane88/01-tensor-operations


'https://jovian.ai/asaane88/01-tensor-operations'

## Function 5 - torch.reshape

Returns an specific shape for a tensor already created; it will have the same data as the original tensor.

In [ ]:
# Example 1 - working
tensor3 = torch.arange(4.)
torch.reshape(tensor3, (2,2))

tensor([[0., 1.],
        [2., 3.]])

First the tensor was created with the arange method (ergo, only 1 dimension).

Then we RESHAPE it with the function and transformed it to a 2 x 2 matrix).

In [ ]:
# Example 2 - working
tensor4 = torch.arange(16,)
torch.reshape(tensor4, (4, 4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

Same case as before, we just reshaped the tensor (tensor4) to a new more usable tensor with desired shape.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.reshape(tensor4, (3, 3))

RuntimeError: shape '[3, 3]' is invalid for input of size 16

Here we tried the same a before, however the shape designated to our original table does't match our original elements displayed.

This function is very powerful and it would surely help with handling of better information regarding children at the partk!

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "asaane88/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/asaane88/01-tensor-operations


'https://jovian.ai/asaane88/01-tensor-operations'

## Conclusion

We covered tools that are simple yet very powerful and will help you during your study of PyTorch.

You will be able to manipulate the Tensors as you which and be able to focus on the greater picture when learning deep process, without having to handle the hassle of hand-writing the Tensor themselves.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
